---
title: "P300 Speller with patient with ALS"
subtitle: "Progetto MOBD 2018/19"
author: "Conidi Andrea, Falvo Simone"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduzione

Lo scopo del progetto è quello di predire correttamente i caratteri corrispondenti a sequenze di stimolazioni provenienti da un'interfaccia BCI.

Il lavoro svolto è stato quello di utilizzare tecniche di classificazione binaria per distinguere le istanze *target* da quelle *non target*. In particolare è stato utilizzato un classificatore di tipo SVM lineare con l'ausilio di tecniche di data augmentation e feature selection, inoltre è stata modificata la funzione di decisione in modo che, in corrispondenza di ogni iterazione di stimolazioni, vengano selezionate come target una sola riga ed una sola colonna.

Il classificatore è stato addestrato su una porzione del dataset fornito, l'altra porzione è stata utilizzata come test ed i risultati finali hanno mostrato...

# Data Understanding
# Data Splitting
# Data Augmentation


## Funzione di decisione

Funzione basata sul massimo invece che sul segno, vengono estratti i decision value ogni 120 istanze del dataset che corrispondono alle 10 iterazioni di un singolo carattere, e per ogni iterazione vengono calcolate la riga e la colonna aventi i decision value massimi
